<?php
$formData 		= $this;
$preservePost 	= Mage::getSingleton('core/session')->getEdformOrderPost();
if (!empty($preservePost)) {
    //print_r($preservePost); exit;
    $formData = $preservePost;
}
$helper = Mage::helper('edform');
?>

	<div class="topLinks">
         
         <a href="<?php echo $helper->getListPastOrderUrl(); ?>">Orders</a> | 
         <?php
         if ($helper->isUserCaAdmin()) {
             ?>
             <a href="<?php echo $helper->getCreateSubAccountUrl(); ?>">Create Sub-Account</a> |
             <?php
         }
         ?>
         <a href="<?php echo $helper->getMyAccountUrl();?>">My Account</a> |
         <a href="<?php echo $helper->getContactUrl(); ?>">Contact Us</a> | 
         <a href="<?php echo $this->getLogoutUrl(); ?>">Logout</a>
     </div>


	
<script language="javascript">
    function preview(orderId) {
        //jQuery(".modal-dialog").css("width", jQuery( window ).width());
        jQuery('#myModal').modal('show').find('.modal-body').html('Loading Order Preview..')
        jQuery('#myModal').modal('show').find('.modal-body').load('<?php echo $helper->getPreviewUrl(); ?>?order_id=' + orderId);
    }
</script>

<div id="myModal" class="modal fade" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header no-print">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <p>Loading..</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<?php
$error = Mage::getSingleton('core/session')->getEdformOrderPostError();
Mage::getSingleton('core/session')->unsEdformOrderPostError();
if (isset($error['message'])) {
?>
    <div class="alert alert-warning">
        <strong>Warning!</strong> <?php echo $error['message']; ?>
    </div>
<?php
} else {
?>
	<div class="alert alert-success">
		<strong>Success!</strong> An order has been placed.
	</div>

	<?php
		$lastOrderId = Mage::getSingleton('customer/session')->getLastEdformOrderId();
		if (is_numeric($lastOrderId)) {
			?>
			<div class="col-lg-2 col-md-2 col-sm-2 mb-2 align-items-center">
				<input type="button" onclick="preview(<?php echo $lastOrderId; ?>);" class="btn btn-primary no-print" value="View Order">
			</div>
			<?php
		}
	?>
<?php 
} 
?>

