<div class="account-login">
    <div class="page-title">
        <h1><?php echo $this->__('Reset Commercial Account (CA) Password') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.login.extra')?>
    <form action="<?php echo $this->getPasswordResetUrl() ?>" method="post" id="forgot-form">
        <div class="col1-set">
            <div class="col-1 new-users">
                <div class="content">
                    <h2><?php echo $this->__('Reset your password here') ?></h2>
                    <p><?php echo $this->__('Please enter your new password below.') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="hidden" name="token" value="<?php echo $token; ?>" />
                                <input type="password" name="password" value="" id="password" class="input-text required-entry validate-length minimum-length-8" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="confirm_password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="confirm_password" value="" id="confirm_password" class="input-text required-entry validate-cpassword" title="<?php echo $this->__('Confirm Password') ?>" />
                            </div>
                        </li>
						<?php echo $this->getChildHtml('form.additional.info'); ?>
                    </ul>
                    <?php if (false) { ?>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <?php } ?>
                    <div class="buttons-set">
                        <p class="back-link"><a href="<?php echo $this->getModuleBaseUrl(); ?>"><small>« </small>Back to Login</a></p>
                        <button type="submit" class="button" title="<?php echo $this->__('Submit') ?>" name="send" id="send2"><span><span><?php echo $this->__('Submit') ?></span></span></button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col2-set">
            <div class="col-1 new-users">

            </div>
            <div class="col-2 registered-users">

            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('forgot-form', true);
    //]]>
    </script>
</div>